### PR TITLE
fix wrong set of HOME to /root

### LINKED ISSUE #43: using `cd ~` returns error
/root dir does not exist

### PR DESCRIPTION
**Pull request by Ccode-lang**
fixes #43 and makes nanorc files findable again

### CODE REVIEW

**Comment by mintsuki** [comment]
This is not the correct fix.

**Comment by Ccode-lang** [comment]
but changing HOME var to a directory that does not exist causes problems

**Comment by JalonSolov** [comment]
Wouldn't the correct fix be to create `/root`, then?

**Comment by Ccode-lang** [comment]
Ok looks like that is done now though

**Pull request closed without merging**
