### PR TITLE
Possible alternative?

### PR DESCRIPTION
**Pull request by Ccode-lang**
I was wondering if this would be a good alternative.  It would be a good fix for the `FIXME`

### CODE REVIEW

**Comment by streaksu** [comment]
The goal of the design is for the shell to restart in case of exit or crash, so the system doesnt come to a stop when one of these things happen.
While a good way to catch the error, in this case we just dont want to catch it, but keep trying.

**Comment by Ccode-lang** [comment]
I will fix this now

**Comment by Ccode-lang** [comment]
Should not be a problem.  If error code 5000 is a bash exit status then we might have a problem.

**Comment by Ccode-lang** [comment]
This is not a good way to do this I'm still experimenting.

**Pull request closed without merging**
