### PR TITLE
Rewrite most C stuff in V

### PR DESCRIPTION
**Pull request by alula**

### CODE REVIEW

**Review by leapofazzam123 — CHANGES_REQUESTED** [review]
Why rewrite entry.c in Assembly? Can you rewrite it in V instead?

**Comment by alula** [comment]
It's just more convenient in this case (and it's what mint suggested before), since V doesn't let you specify which executable section should be used for something.

**Comment by leapofazzam123** [comment]
Doesn't linker exists

**Comment by alula** [comment]
we could add a hack in ldscript but why if you can do it in few lines of trivial assembly?

**Comment by mintsuki** [comment]
Remove blob.patch from this PR

**Comment by alula** [comment]
It has some changes applied, but I can base it off main

**Comment by alula** [comment]
fixed

**Pull request merged**
