### PR TITLE
Update code

### PR DESCRIPTION
**Pull request by vinothkumar02**
I have updated the logo used in our application to better reflect our brand and messaging. I believe this change will help improve our visual identity and strengthen our user experience.

Please take a look at the new logo and let me know if you have any feedback or concerns. I'm open to making adjustments if necessary.

"Updated the README file to include new information and improve the overall formatting. Please review and let me know if any further changes are needed."

Thanks,

### CODE REVIEW

**Comment by vnothkumar** [comment]
@spytheman @elimisteve @mvlootman @medvednikov

**Comment by Delta456** [comment]
Can you attach a screenshot for better visibility?

**Comment by vnothkumar** [comment]
> Can you attach a screenshot for better visibility?

fetch

**Comment by elimisteve** [comment]
@vnothkumar How about attaching a screenshot of how it looked before so we can compare? Thanks.

**Comment by vnothkumar** [comment]
@Delta456 @elimisteve 
fetch2

**Pull request closed without merging**
