### PR TITLE
fix some small things

### PR DESCRIPTION
**Pull request by Ccode-lang**
This pull fixes a few small annoyances with ufetch.

### CODE REVIEW

**Comment by Ccode-lang** [comment]
image from Ccode's pi
No change in how it actually looks.

**Comment by mintsuki** [comment]
LGTM

**Comment by Ccode-lang** [comment]
just found a bug with this:
Snip20211123_10
This is with Vinix. Next time I should only test with vinix.

**Comment by Ccode-lang** [comment]
I will open a pull later to fix this.

**Comment by Ccode-lang** [comment]
The script should work the way it is right now but it does not put the os name.

**Pull request merged**
